[[Singular]]
arch = "aarch64"
git-tree-sha1 = "86c95e0be145e5322fa9d7dd5b61c6fdd73d3edd"
os = "macos"

    [[Singular.download]]
    sha256 = "3011c9257b03a70a86cc866ae4d3da565248f20404ee7f7fe744d239423dbc9d"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.500+0/Singular.v404.101.500.aarch64-apple-darwin.tar.gz"
[[Singular]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cd9fe371a6f58ad455b6b346b0cbe8bf194bba4a"
libc = "glibc"
os = "linux"

    [[Singular.download]]
    sha256 = "9ce36684069fc2ef3fa828afeb6d34aa1de67f39c7a98c60a09c937e0be79b94"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.500+0/Singular.v404.101.500.aarch64-linux-gnu-cxx11.tar.gz"
[[Singular]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "87525d59781ab14415352944dbfba627187589c0"
libc = "musl"
os = "linux"

    [[Singular.download]]
    sha256 = "e9f83991a106d7dbd35aa4b02e93039ecd8a7e90a68795043f16c581eca25017"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.500+0/Singular.v404.101.500.aarch64-linux-musl-cxx11.tar.gz"
[[Singular]]
arch = "aarch64"
git-tree-sha1 = "1c7840edf95bad9e783f056346f0e375969648e9"
os = "freebsd"

    [[Singular.download]]
    sha256 = "2714dccbd137f4b34d37e4dc767c0a7e4a933306621960356127504cdc5faa8d"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.500+0/Singular.v404.101.500.aarch64-unknown-freebsd.tar.gz"
[[Singular]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ba4ef533e5fb25c17995d05ae8b04da9454dd539"
libc = "glibc"
os = "linux"

    [[Singular.download]]
    sha256 = "52cbda79be2a1ee4c34456bfdf62e2b3bc8eb72eb573d83e09ce573855124d15"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.500+0/Singular.v404.101.500.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[Singular]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3e6f5accfff3dd804bcbac01c39f827b9473fcf6"
libc = "musl"
os = "linux"

    [[Singular.download]]
    sha256 = "e6e287a607930d393e82c741757ed197a6d07d865eaa9dc73d6eff9990481aab"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.500+0/Singular.v404.101.500.armv6l-linux-musleabihf-cxx11.tar.gz"
[[Singular]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "22b729148bcf02a28d0bcf01bf2ba5ba9cc19624"
libc = "glibc"
os = "linux"

    [[Singular.download]]
    sha256 = "5b9c257a5b960851d2bbc8903f621333f070eb984d6c4860e885fade8a0a70ba"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.500+0/Singular.v404.101.500.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Singular]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dbefa5994f4bf0764a3a7e3c4a7d6bd852df471d"
libc = "musl"
os = "linux"

    [[Singular.download]]
    sha256 = "2598a84bf3a84230960614c983457694eea6a642b3d53ad2fd15d1b263aa952d"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.500+0/Singular.v404.101.500.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Singular]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7fe5b323595e05e3f28bc31876735797d9a462cf"
libc = "glibc"
os = "linux"

    [[Singular.download]]
    sha256 = "22d3609e9f856ffa8af8a1ffa182f1e17ec21ce1398a54345d50b6aa6d9ffb71"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.500+0/Singular.v404.101.500.i686-linux-gnu-cxx11.tar.gz"
[[Singular]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "67a1b30cdc3c976a0c4f803cb69082e96da19efe"
libc = "musl"
os = "linux"

    [[Singular.download]]
    sha256 = "6f9cc9e0868244dc88b51a94889465b162bb22e42119c6e2447f6bf9be023ce9"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.500+0/Singular.v404.101.500.i686-linux-musl-cxx11.tar.gz"
[[Singular]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0e0021e2888f85c97e22e50609145240e993d818"
libc = "glibc"
os = "linux"

    [[Singular.download]]
    sha256 = "69669c6ad5bdd2252d6ba15775461af51ca52eb170e6182c9bf250cacc4bced2"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.500+0/Singular.v404.101.500.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Singular]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ffe2ab4f0a611f2014b2f2912faa078551915a99"
libc = "glibc"
os = "linux"

    [[Singular.download]]
    sha256 = "0c8ecb9566cc6f5700b0a6ac9b030c0b893db3fe4b5fe0c8ffe1afe29fab6ddd"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.500+0/Singular.v404.101.500.riscv64-linux-gnu-cxx11.tar.gz"
[[Singular]]
arch = "x86_64"
git-tree-sha1 = "d40243d1ea9a59f69c7cb0cef817c7e41702f756"
os = "macos"

    [[Singular.download]]
    sha256 = "b0d309934be852335a2cf74081fff21cb990c8b9753c43783bce49a2b861dcba"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.500+0/Singular.v404.101.500.x86_64-apple-darwin.tar.gz"
[[Singular]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "11e7ed20507a45c9138c596325f9ed97227027a9"
libc = "glibc"
os = "linux"

    [[Singular.download]]
    sha256 = "e648af21847fba7b8873f299d945732e804fefa0392fa721c100c797badd02b4"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.500+0/Singular.v404.101.500.x86_64-linux-gnu-cxx11.tar.gz"
[[Singular]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a3db8f445ed8c40cc5b95791105f9e4c677df26d"
libc = "musl"
os = "linux"

    [[Singular.download]]
    sha256 = "df23ea0bce1b73faefc77ea28bafe5202bcd15178be6abfaa342096fd71f06cc"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.500+0/Singular.v404.101.500.x86_64-linux-musl-cxx11.tar.gz"
[[Singular]]
arch = "x86_64"
git-tree-sha1 = "1bed6186af6f9150390ab1f204cce960c265f74f"
os = "freebsd"

    [[Singular.download]]
    sha256 = "d8479067f4c6591c485abc1990234481473804614e4b5d76e4af3fd75657e3a7"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.500+0/Singular.v404.101.500.x86_64-unknown-freebsd.tar.gz"
