[[Singular]]
arch = "aarch64"
git-tree-sha1 = "770e5383332394f5ba54e3a583d07722c51520c2"
os = "macos"

    [[Singular.download]]
    sha256 = "059157c2c156e134c60824da6cfb9ce12dc1a5b9fd85b9421f49efba902e4d3c"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.501+0/Singular.v404.101.501.aarch64-apple-darwin.tar.gz"
[[Singular]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "49916ee139735d734efc34e4126e5ff998279b67"
libc = "glibc"
os = "linux"

    [[Singular.download]]
    sha256 = "5229f5ceadd054e2cf55cac725a4277b9cae2bf6c744111389bcd03e7a18a1fe"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.501+0/Singular.v404.101.501.aarch64-linux-gnu-cxx11.tar.gz"
[[Singular]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d573234b262a7ac522a04335d68aa0b44ebdc742"
libc = "musl"
os = "linux"

    [[Singular.download]]
    sha256 = "886cba233aaee824492429247cb0a4de225a546f4700729272319df87717fb33"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.501+0/Singular.v404.101.501.aarch64-linux-musl-cxx11.tar.gz"
[[Singular]]
arch = "aarch64"
git-tree-sha1 = "d8448150362ec382e3952246fe9e69939d70d22b"
os = "freebsd"

    [[Singular.download]]
    sha256 = "200b5e79ec8742c356bf904ebdbdb9d21b7100ded9034642cc4b51ed53c8ea06"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.501+0/Singular.v404.101.501.aarch64-unknown-freebsd.tar.gz"
[[Singular]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "719c3bece5e687fd6bf63101d0081a554338bb7a"
libc = "glibc"
os = "linux"

    [[Singular.download]]
    sha256 = "906f8e72420146adfdca6e988518ca34f57606ccf4ec77b7247690fb0f3b1080"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.501+0/Singular.v404.101.501.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[Singular]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c5843343b368501c6d87b06d6b4c9964d28bede7"
libc = "musl"
os = "linux"

    [[Singular.download]]
    sha256 = "6f1a9815d3d1ce78dfef3d9086652eb96ba3b37de4ae9b9ce1f7f1dc9bb963c5"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.501+0/Singular.v404.101.501.armv6l-linux-musleabihf-cxx11.tar.gz"
[[Singular]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e120653576993443041cd000a3766375811d5ba5"
libc = "glibc"
os = "linux"

    [[Singular.download]]
    sha256 = "afe5a064dd37dfcb532625c4a80f1d9ffcef55de53e53afda8b53c9a0c9723d8"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.501+0/Singular.v404.101.501.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Singular]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ee86374c53ee2106d98106888a6a2f9edbfc9879"
libc = "musl"
os = "linux"

    [[Singular.download]]
    sha256 = "0c1fcf366b2fbc0f9c9612c88816dbbd574e3f3dd186ddea98ec0529aa920f48"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.501+0/Singular.v404.101.501.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Singular]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d81af22171a583101b768fa0c5ea6979a1a56272"
libc = "glibc"
os = "linux"

    [[Singular.download]]
    sha256 = "020c5b50bbdad33c783f3c588800b43ea38dc32bf3af6135a006e30554053a7c"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.501+0/Singular.v404.101.501.i686-linux-gnu-cxx11.tar.gz"
[[Singular]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bea06bb4695a534d4cd79c5ee6dead4944424b1e"
libc = "musl"
os = "linux"

    [[Singular.download]]
    sha256 = "e7aa483d5760e1c6a9d5e6b6fb47dfc2307f0585a9495daa8075a624036e2f51"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.501+0/Singular.v404.101.501.i686-linux-musl-cxx11.tar.gz"
[[Singular]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "96e12b3f2b76a9bbe233cc095fd6fa6b5002f659"
libc = "glibc"
os = "linux"

    [[Singular.download]]
    sha256 = "ae7754b29902923635dc06aabfbca9e6c98349ceadfef1b8c2cb0d461d6954ad"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.501+0/Singular.v404.101.501.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Singular]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6d747b76532fe779326cf41cd88925284dd372e8"
libc = "glibc"
os = "linux"

    [[Singular.download]]
    sha256 = "eecc170ae9afecbfaf3f9c828f23c7f14e1ad3f121914708e0292cdc2a332bd8"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.501+0/Singular.v404.101.501.riscv64-linux-gnu-cxx11.tar.gz"
[[Singular]]
arch = "x86_64"
git-tree-sha1 = "ae876193bfbf5021e3591df142e165bba477a994"
os = "macos"

    [[Singular.download]]
    sha256 = "fee206141b69dc44b5ace491d505e350720b99197e9ffde28785c7fb46448b60"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.501+0/Singular.v404.101.501.x86_64-apple-darwin.tar.gz"
[[Singular]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fbac7aa99577b4734fb1307a7b5887a22d73c796"
libc = "glibc"
os = "linux"

    [[Singular.download]]
    sha256 = "467fc5059211f1b2958944efd0bafc9f8321c0b67a1e22a2f44fdcd0a582969f"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.501+0/Singular.v404.101.501.x86_64-linux-gnu-cxx11.tar.gz"
[[Singular]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0f7db6a113d0c813b3e807caccdb85de5a22a8ec"
libc = "musl"
os = "linux"

    [[Singular.download]]
    sha256 = "595d38f305d3329f67f44313850ef3ef4bb0e728f51baf4f563d59dc9395e41d"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.501+0/Singular.v404.101.501.x86_64-linux-musl-cxx11.tar.gz"
[[Singular]]
arch = "x86_64"
git-tree-sha1 = "4659495495f0635ebbafe7dda6cc6d5b743fd2e7"
os = "freebsd"

    [[Singular.download]]
    sha256 = "506817929c8e11b6897a82c545a2dbc19fd44688902404a64336f5df5a5e600b"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.501+0/Singular.v404.101.501.x86_64-unknown-freebsd.tar.gz"
