[[Singular]]
arch = "aarch64"
git-tree-sha1 = "4ad9f90e1613ebe941d4b2c0e82f768307133504"
os = "macos"

    [[Singular.download]]
    sha256 = "92bcf373f5714accb820510762de1ce2098be1c6a7ce566ae9f318725897ed4f"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.502+0/Singular.v404.101.502.aarch64-apple-darwin.tar.gz"
[[Singular]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c931bd46941488a9ca6fdd31807980c039e0a78d"
libc = "glibc"
os = "linux"

    [[Singular.download]]
    sha256 = "298f9389e94f8d25fc83471f9ad61ac77494e74d4075423d12789c8224a144f5"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.502+0/Singular.v404.101.502.aarch64-linux-gnu-cxx11.tar.gz"
[[Singular]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2be904e22209706073cbba58ecef3360d3734cf0"
libc = "musl"
os = "linux"

    [[Singular.download]]
    sha256 = "d9bdfb4fabee1bdb6dbcb70578cf85c7641e7acd2d1a3b77bc5ffca6a2ba758f"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.502+0/Singular.v404.101.502.aarch64-linux-musl-cxx11.tar.gz"
[[Singular]]
arch = "aarch64"
git-tree-sha1 = "4650b8a4054b7cfdae80a5b7a758416bff7bfe76"
os = "freebsd"

    [[Singular.download]]
    sha256 = "41230b3e6335cdadd20d7e0605aa2d002c516445d61cb33057603ea559f85dc5"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.502+0/Singular.v404.101.502.aarch64-unknown-freebsd.tar.gz"
[[Singular]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0a2b4b96d17ada63a80446db3d439ecfa1752fe0"
libc = "glibc"
os = "linux"

    [[Singular.download]]
    sha256 = "2127b8fcd42b61dbe8a864b4a7222e5535a28107fdb577c4cc58b11baa0a89f8"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.502+0/Singular.v404.101.502.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[Singular]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2f5a71c423d4e0cf7765b7da5aa4b1686538de22"
libc = "musl"
os = "linux"

    [[Singular.download]]
    sha256 = "99efc176452680dad1c41ad803865cdaa66f8fb4005db5c5860a5b64ab2e0b23"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.502+0/Singular.v404.101.502.armv6l-linux-musleabihf-cxx11.tar.gz"
[[Singular]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "129c75454b7b2e953b0dec4f5b47d4f6f84088ef"
libc = "glibc"
os = "linux"

    [[Singular.download]]
    sha256 = "3e0742b20bd1f4e6d165d2b611279b37033cd12c358fe3002cf828c5320aa7aa"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.502+0/Singular.v404.101.502.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Singular]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "240560d02e16c5eb7da85f4c79bfbafb591de1c1"
libc = "musl"
os = "linux"

    [[Singular.download]]
    sha256 = "e3d9cdd4e5aa188961fafd9744bae11c047639c6762c32d8dae70ac9b590c72e"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.502+0/Singular.v404.101.502.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Singular]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fdc7720a305bf7851a0139b7142e332776aa7eb1"
libc = "glibc"
os = "linux"

    [[Singular.download]]
    sha256 = "38e45b9435b6bfa7812bbfecb0cf9146091c8d3e0f04775d7b8c22940233f66c"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.502+0/Singular.v404.101.502.i686-linux-gnu-cxx11.tar.gz"
[[Singular]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "869963a9b351171ddad315ba643d5e05efad7605"
libc = "musl"
os = "linux"

    [[Singular.download]]
    sha256 = "33f35ef2850a745ec61ee77531b5649af1c3a0ee771ae5ef58ff8b2fda135a57"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.502+0/Singular.v404.101.502.i686-linux-musl-cxx11.tar.gz"
[[Singular]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fbfdc8a342a0e044460b37120eb70e448484b654"
libc = "glibc"
os = "linux"

    [[Singular.download]]
    sha256 = "675f2bfab8bf66b44d94e66ff97c4cbe38fcd481e142f65c6fd2e73c88a1f66e"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.502+0/Singular.v404.101.502.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Singular]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "745941e40a4a82f9be70b4663019350cc1e3f695"
libc = "glibc"
os = "linux"

    [[Singular.download]]
    sha256 = "c7094954c057def6ef678a3dba4680d796b85d719a681c0ce30d7ce6c38c04e1"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.502+0/Singular.v404.101.502.riscv64-linux-gnu-cxx11.tar.gz"
[[Singular]]
arch = "x86_64"
git-tree-sha1 = "95130408f210750b7b0595008b60de59e9636815"
os = "macos"

    [[Singular.download]]
    sha256 = "fe53e551b4485f6c82c966a653021fa5f2d0106b0a738617d538d20a25343a7d"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.502+0/Singular.v404.101.502.x86_64-apple-darwin.tar.gz"
[[Singular]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5c1de36ea8dc40646ce867e0261b0c488c153c1b"
libc = "glibc"
os = "linux"

    [[Singular.download]]
    sha256 = "1373cbab588add088dfdc33b511c77676e380971ddd2971978411b5268ca8cc7"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.502+0/Singular.v404.101.502.x86_64-linux-gnu-cxx11.tar.gz"
[[Singular]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e9a29b47fa8d747a96c4c254ab4dbeed7c39e02b"
libc = "musl"
os = "linux"

    [[Singular.download]]
    sha256 = "810730f137ff0d1946613afa36a629a2dc641d76229389867e6f6a1aff8fc72b"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.502+0/Singular.v404.101.502.x86_64-linux-musl-cxx11.tar.gz"
[[Singular]]
arch = "x86_64"
git-tree-sha1 = "0e383b5cc018bd4cf8b78a16a8c65b850e3736c5"
os = "freebsd"

    [[Singular.download]]
    sha256 = "dde230e1389bc61be9b445c1b8b4ee46a0f0cc60182129630078e9807a1a6d96"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.502+0/Singular.v404.101.502.x86_64-unknown-freebsd.tar.gz"
