[[Singular]]
arch = "aarch64"
git-tree-sha1 = "c4ac99fe6300c31388a93d490be03202c3fa3fd1"
os = "macos"

    [[Singular.download]]
    sha256 = "e008ec631e50bdc301d01a280d0fc8ea2df02cfbefe1e48b44660bc755fd4885"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.301+0/Singular.v404.101.301.aarch64-apple-darwin.tar.gz"
[[Singular]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a9778d4961b740db86ee4510f7838399de9e536b"
libc = "glibc"
os = "linux"

    [[Singular.download]]
    sha256 = "c6d9fb307d0d5f28bbcce3d64aef23e78cf9b9cfbeed534a997fc4ea69ed4639"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.301+0/Singular.v404.101.301.aarch64-linux-gnu-cxx03.tar.gz"
[[Singular]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e116f119664695abfafee7bae629503a3306560c"
libc = "glibc"
os = "linux"

    [[Singular.download]]
    sha256 = "ea4e4d22533ccd29d20b2c802abeebf8f9fa44e766451a9f0b0eb16749f31caa"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.301+0/Singular.v404.101.301.aarch64-linux-gnu-cxx11.tar.gz"
[[Singular]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "993483d0255fc8f99f47f6024c034e3d221065f3"
libc = "musl"
os = "linux"

    [[Singular.download]]
    sha256 = "5db4905a254c691c1a2481f9488bdf6b541378eba48ecc719dc2b4eeaab604cc"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.301+0/Singular.v404.101.301.aarch64-linux-musl-cxx03.tar.gz"
[[Singular]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2537c3a892489cbffe487aa98da6f1111d924ce7"
libc = "musl"
os = "linux"

    [[Singular.download]]
    sha256 = "ecb045826a6b263c00cfaa62e63506a96aabf362a63b23f5d9b4c4a802f6c26a"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.301+0/Singular.v404.101.301.aarch64-linux-musl-cxx11.tar.gz"
[[Singular]]
arch = "aarch64"
git-tree-sha1 = "02020e805b45d62e8bc74698737836eefcdb517a"
os = "freebsd"

    [[Singular.download]]
    sha256 = "12510455d99c31b2f8b395e507993176664bd8c096b69a2a5e09cbf2e354318f"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.301+0/Singular.v404.101.301.aarch64-unknown-freebsd.tar.gz"
[[Singular]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3eec3a90cbef2a3055c2b0c8e9a231138e2ab834"
libc = "glibc"
os = "linux"

    [[Singular.download]]
    sha256 = "1f71b00f538fe80204e916fb1e28016bb23da37c7b05af69e780d4842dee0cb7"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.301+0/Singular.v404.101.301.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[Singular]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4652eca80fffb4504340b3317637e15e01279d7a"
libc = "glibc"
os = "linux"

    [[Singular.download]]
    sha256 = "ea6f0032bdd911536056d8942eef9286ce314e7819d0e56d7e6c8eff9d164c68"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.301+0/Singular.v404.101.301.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[Singular]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6eec77488ec2d3646f117c65539ebae041db1417"
libc = "musl"
os = "linux"

    [[Singular.download]]
    sha256 = "25f00d32d3d006908ff514279f0c3609ed73993adef5ee0c95d864d060ce1650"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.301+0/Singular.v404.101.301.armv6l-linux-musleabihf-cxx03.tar.gz"
[[Singular]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cd72cd937e10fa7d1e9f7bec6af29db64bbf3e4e"
libc = "musl"
os = "linux"

    [[Singular.download]]
    sha256 = "65ec1323be1019670ff1209bb6ac9af6126418a2dd064d39fe4edf8e50ad1f2d"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.301+0/Singular.v404.101.301.armv6l-linux-musleabihf-cxx11.tar.gz"
[[Singular]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "06656fb0205ee3c1ba40c7ee518ea1a2866addb9"
libc = "glibc"
os = "linux"

    [[Singular.download]]
    sha256 = "e663e67d16036bade4353ded39282066ee189281bbdfb2699ede563b3ce62c32"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.301+0/Singular.v404.101.301.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Singular]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b936bd607a176c75bc53f024cd34578b51b46e09"
libc = "glibc"
os = "linux"

    [[Singular.download]]
    sha256 = "965deb66b29f229c41bd99b19f7f4b784dea822ee8828d4fdde4adcd0dcc764e"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.301+0/Singular.v404.101.301.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Singular]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6b89e94677b8a188834c752ec3e15f1d43e29051"
libc = "musl"
os = "linux"

    [[Singular.download]]
    sha256 = "2b8488659df97852571195d515ab589a5b273baaaf34bb24a094181dc4a6bf8c"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.301+0/Singular.v404.101.301.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Singular]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d6d7617a3bdfdb3389cf3f52aadddd64f547f331"
libc = "musl"
os = "linux"

    [[Singular.download]]
    sha256 = "3a79df56bdd89fabbb98aa6094e2f1a9bf1d1130158a0234f6b83ed03c730ef1"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.301+0/Singular.v404.101.301.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Singular]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f6e7476d937cadd76d3acefabc8474ae1bad19d2"
libc = "glibc"
os = "linux"

    [[Singular.download]]
    sha256 = "e3439c64096feb580dbe9463f767b857f65e6f3da09e079dd76da6dca5b1a1cf"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.301+0/Singular.v404.101.301.i686-linux-gnu-cxx03.tar.gz"
[[Singular]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1f3ac7a5ee34df716c8ac08719eb50307e0339bb"
libc = "glibc"
os = "linux"

    [[Singular.download]]
    sha256 = "de51c572e3106f549312298ac42b9ab7d3004dacc1f1ee92552bc437739253b1"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.301+0/Singular.v404.101.301.i686-linux-gnu-cxx11.tar.gz"
[[Singular]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ce2965f63050d87389ac9989190fbe01000cc057"
libc = "musl"
os = "linux"

    [[Singular.download]]
    sha256 = "03a19f347110af6958ec3bd277bdb3f8baaa3dc7cbf8d44220db7c8056299a19"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.301+0/Singular.v404.101.301.i686-linux-musl-cxx03.tar.gz"
[[Singular]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2448b8932d916c32668e5c8ca5957f176e7c6166"
libc = "musl"
os = "linux"

    [[Singular.download]]
    sha256 = "c60f4855451ead67a93b44c1c78fc4962eeb02ce1a814b11b7d8395981b93073"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.301+0/Singular.v404.101.301.i686-linux-musl-cxx11.tar.gz"
[[Singular]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "aa08a0dca2e1e13aca09c55f21b173cd11360108"
libc = "glibc"
os = "linux"

    [[Singular.download]]
    sha256 = "b9b493d3ac7665f3a16af661da2cd46935195abf94556ed52b0c785d12610ed6"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.301+0/Singular.v404.101.301.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Singular]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "08619f69b201c91f06201f19fdc2d44147752ecd"
libc = "glibc"
os = "linux"

    [[Singular.download]]
    sha256 = "edab20071f25b8455fc96ab6fdb2c768891da69c95131234e90b69ffcca07ebe"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.301+0/Singular.v404.101.301.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Singular]]
arch = "riscv64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7b78e6e28fb528ef6aa8540db6c3fc8b5be1a3fc"
libc = "glibc"
os = "linux"

    [[Singular.download]]
    sha256 = "90ea8785df7bdb0a11c015f532a945cb4fbf79b78b198fbdd1fcd0bd9a6a6773"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.301+0/Singular.v404.101.301.riscv64-linux-gnu-cxx03.tar.gz"
[[Singular]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a02315bb7f143897f2c3a300a8acd99ee6eb301f"
libc = "glibc"
os = "linux"

    [[Singular.download]]
    sha256 = "212edae472e560a7c8a3c2b575b1483952267e2c1539689de96d491ec1bab99e"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.301+0/Singular.v404.101.301.riscv64-linux-gnu-cxx11.tar.gz"
[[Singular]]
arch = "x86_64"
git-tree-sha1 = "e66b5c5de4ab86dee46c76e2c61738aa05dbb7f7"
os = "macos"

    [[Singular.download]]
    sha256 = "798b83c0a27bee8e68c1ff7b14641e6879e3bdcce7e3097896b2150ef8b49eeb"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.301+0/Singular.v404.101.301.x86_64-apple-darwin.tar.gz"
[[Singular]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9c7049091d15aceffe9af88c1c377b08c029bda6"
libc = "glibc"
os = "linux"

    [[Singular.download]]
    sha256 = "fecaef91f4a61934699eef45fbdd804d2c197e4b4644926711cc73975de90599"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.301+0/Singular.v404.101.301.x86_64-linux-gnu-cxx03.tar.gz"
[[Singular]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "be995df069af687a54983db6509330b199e5471d"
libc = "glibc"
os = "linux"

    [[Singular.download]]
    sha256 = "c58a9cb93bf50af1988fadedaa6f928b1e365f90d6513c193ee8ef8763f3f6cb"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.301+0/Singular.v404.101.301.x86_64-linux-gnu-cxx11.tar.gz"
[[Singular]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4f26ce33f2e47fb2c4dd8b6dbd4b5f02d6c30cfc"
libc = "musl"
os = "linux"

    [[Singular.download]]
    sha256 = "b2e71fd32febeea4f4d11921305cc03886245fda73535bf9660d87726504e0dd"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.301+0/Singular.v404.101.301.x86_64-linux-musl-cxx03.tar.gz"
[[Singular]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4c7fab4ec9c5124891ec1f48ab2581d01b621b65"
libc = "musl"
os = "linux"

    [[Singular.download]]
    sha256 = "dc1a4f695d053c4108f44d6cb02d698a2a6ea0a7ab2cf4585833f6425dfdcabf"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.301+0/Singular.v404.101.301.x86_64-linux-musl-cxx11.tar.gz"
[[Singular]]
arch = "x86_64"
git-tree-sha1 = "9804df46810b5d1b8cd5f3bb566f484a5f0c30b7"
os = "freebsd"

    [[Singular.download]]
    sha256 = "e4a07f5ab260ef7c372a0fd9c533b87ce36870ca10b24a3a064758c3ca12a6cf"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.301+0/Singular.v404.101.301.x86_64-unknown-freebsd.tar.gz"
