[[Singular]]
arch = "aarch64"
git-tree-sha1 = "4264389601a1d9e73e35fcbce1aea57e3cf6fa3a"
os = "macos"

    [[Singular.download]]
    sha256 = "fbc4bf0a50b8a8a5eba03d9ba59ad4715ebd1273b0566b3227926557002a2d60"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.400+0/Singular.v404.101.400.aarch64-apple-darwin.tar.gz"
[[Singular]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7336f519ecc1b02caa8b37452c81da08de96ca28"
libc = "glibc"
os = "linux"

    [[Singular.download]]
    sha256 = "09e1aefcf0462c211373d40c299327a430d96420569fec9a3c9bef58ac717fc1"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.400+0/Singular.v404.101.400.aarch64-linux-gnu-cxx03.tar.gz"
[[Singular]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e39aee371426eedf3096c75fd9e8d4a75ace03bb"
libc = "glibc"
os = "linux"

    [[Singular.download]]
    sha256 = "3a5f45b3698f598b1a2b5d0c3def52b42dec789778ba3128762a8c678ae3c849"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.400+0/Singular.v404.101.400.aarch64-linux-gnu-cxx11.tar.gz"
[[Singular]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "097e13e6e5bf218fb7e04f0cb896da718f82b108"
libc = "musl"
os = "linux"

    [[Singular.download]]
    sha256 = "bcc50c743218c0c620f8c5bc57ddc1016194ce668befc363c65f58968c51f624"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.400+0/Singular.v404.101.400.aarch64-linux-musl-cxx03.tar.gz"
[[Singular]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e230a18362b2653ab79e976758032523c74bced2"
libc = "musl"
os = "linux"

    [[Singular.download]]
    sha256 = "3274948254160954e8a52cbe18009594594b52d9d298ebbc485002cb6bf4df3d"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.400+0/Singular.v404.101.400.aarch64-linux-musl-cxx11.tar.gz"
[[Singular]]
arch = "aarch64"
git-tree-sha1 = "7f184ddfe03eb653aa1cd1a174e0b7b0913f54a3"
os = "freebsd"

    [[Singular.download]]
    sha256 = "def76a8f64a7cb0a6c29c14778e79c3eae762560b0bf2e007511cd05c8cd420d"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.400+0/Singular.v404.101.400.aarch64-unknown-freebsd.tar.gz"
[[Singular]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "440e7b5b35114bbbe437ff5bb2db2dde3edbb4c7"
libc = "glibc"
os = "linux"

    [[Singular.download]]
    sha256 = "a4a540d11d90666ef74555541d93cca806d2cd876109efa3922f3d95909889c2"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.400+0/Singular.v404.101.400.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[Singular]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dd98a0cd8b7363600b8d02c6609c88e7228247fe"
libc = "glibc"
os = "linux"

    [[Singular.download]]
    sha256 = "45e47b00e6dfc16780002bd0a37a3a041e7db2ebb8e7a9bb200028c4d85ff972"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.400+0/Singular.v404.101.400.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[Singular]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "befd0cd9ec716260535efd9ad33998f0a10aae3c"
libc = "musl"
os = "linux"

    [[Singular.download]]
    sha256 = "36300913fd577c13308e52ed24b825f9d2f6bb947ec5a6393bfc82018b869322"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.400+0/Singular.v404.101.400.armv6l-linux-musleabihf-cxx03.tar.gz"
[[Singular]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6b73941599313013da6270555ab8875f4d15645c"
libc = "musl"
os = "linux"

    [[Singular.download]]
    sha256 = "377bebecea5e0e734f5ff8cb7589db1eb39e7b7ffdf938f951880c0f7362dd32"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.400+0/Singular.v404.101.400.armv6l-linux-musleabihf-cxx11.tar.gz"
[[Singular]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1fa4d55397b3355fbd847e83a0ea9062762d2a8b"
libc = "glibc"
os = "linux"

    [[Singular.download]]
    sha256 = "fd02a0c92a65243e76c71df73c7c015eeae8f3eb7258a10df1198e1984ac2f2f"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.400+0/Singular.v404.101.400.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Singular]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cb8d36b7f57d3de7fa8767461086d64603de577f"
libc = "glibc"
os = "linux"

    [[Singular.download]]
    sha256 = "ccf0a8e1bae3c3e516c619a8c7be671a247db2458f01e9fbcdf900aa1ee0bc90"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.400+0/Singular.v404.101.400.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Singular]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0d36cc5134268bf3df2ffa3dcca84b2585c2164a"
libc = "musl"
os = "linux"

    [[Singular.download]]
    sha256 = "498481d533e4b513f217dfd9279a8b14e6a5a0cf446ad683dbe9f0263f9cfc27"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.400+0/Singular.v404.101.400.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Singular]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "72c0be566d7e1580dbfc32c40611d2707e8d98e0"
libc = "musl"
os = "linux"

    [[Singular.download]]
    sha256 = "fe387ddc88ae527eb0c399a245ad6fd6521543587a336e9ee2c60f631db4ade6"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.400+0/Singular.v404.101.400.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Singular]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a2c697d7ec37f63527fee3c5145c25115129f7c2"
libc = "glibc"
os = "linux"

    [[Singular.download]]
    sha256 = "92e2c94adaee388d21991964c344fd699877b18af990cd32dd1ad12f189a588f"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.400+0/Singular.v404.101.400.i686-linux-gnu-cxx03.tar.gz"
[[Singular]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "89d964fbc0fb858082f70b2203f1fca78d6e721c"
libc = "glibc"
os = "linux"

    [[Singular.download]]
    sha256 = "3d8b08bc37548a23efae9ce992535eeee78ceaddbec12b7d3b177288980b2b1d"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.400+0/Singular.v404.101.400.i686-linux-gnu-cxx11.tar.gz"
[[Singular]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "222586ad4cf206c338dd81896d6ac62d7ec2ec56"
libc = "musl"
os = "linux"

    [[Singular.download]]
    sha256 = "04a4b3917f3dc7a9ae2313bbe8bc9fca82351d13c3db8d8bc6283afe9818ee86"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.400+0/Singular.v404.101.400.i686-linux-musl-cxx03.tar.gz"
[[Singular]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7f016d9a10b721db42f855844dda146742185143"
libc = "musl"
os = "linux"

    [[Singular.download]]
    sha256 = "cca32d921de291ac0f3a2f674b3171fa6b08523095f9d1816612fe72bc37e510"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.400+0/Singular.v404.101.400.i686-linux-musl-cxx11.tar.gz"
[[Singular]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "68fbddc3b2c2e63f3b48c35d808e6b478e19bf18"
libc = "glibc"
os = "linux"

    [[Singular.download]]
    sha256 = "ddd4de6dcbb1edd297b70de88c1f81127e64beb15ae098749d8c2c139eeb5440"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.400+0/Singular.v404.101.400.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Singular]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "49141210837f99e6dd0162c2ba6020349b0b4265"
libc = "glibc"
os = "linux"

    [[Singular.download]]
    sha256 = "13af424052192c8ef63bb31b6cbe9c28e23e26b254cfeb2112ac96f2ff343ea9"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.400+0/Singular.v404.101.400.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Singular]]
arch = "riscv64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5e1238b8caaabeb53a4e6e335bd9d27ee44adf27"
libc = "glibc"
os = "linux"

    [[Singular.download]]
    sha256 = "ce098e9798069f670c8f02b730ad9a81518b80aa0e9aa450e96841cf029a26fc"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.400+0/Singular.v404.101.400.riscv64-linux-gnu-cxx03.tar.gz"
[[Singular]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "012c48736e64ca84ebb10ad30bdd93605b45c263"
libc = "glibc"
os = "linux"

    [[Singular.download]]
    sha256 = "9aa01de67d6e09898766f129440ae61480ff87e8e6ec91d20005fcbe367173dc"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.400+0/Singular.v404.101.400.riscv64-linux-gnu-cxx11.tar.gz"
[[Singular]]
arch = "x86_64"
git-tree-sha1 = "1f4026dc374ff5c31875808d6d8c24efecd5c8b6"
os = "macos"

    [[Singular.download]]
    sha256 = "feb00368d807babb7fb9d2989002ed839cb56267a5a0a72907b926ecdb4756a9"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.400+0/Singular.v404.101.400.x86_64-apple-darwin.tar.gz"
[[Singular]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0b2e5c571680e04bda266d5fb5324f6213c53c9b"
libc = "glibc"
os = "linux"

    [[Singular.download]]
    sha256 = "1eeae97f6c5c1e75c6d34fc27dca68bc3627542d0c264659b8eebe04508bbc3d"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.400+0/Singular.v404.101.400.x86_64-linux-gnu-cxx03.tar.gz"
[[Singular]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "996ebd967d6e70c3c10e610854d7d8beac6cd0ac"
libc = "glibc"
os = "linux"

    [[Singular.download]]
    sha256 = "618881d6606b2073ea1f4daed2aed66592f1beb650d02f4e148cf4bf48dcad5c"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.400+0/Singular.v404.101.400.x86_64-linux-gnu-cxx11.tar.gz"
[[Singular]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5cda8b38d721847286cb5cfa0672d57ecabb3ecb"
libc = "musl"
os = "linux"

    [[Singular.download]]
    sha256 = "4e2f2967f1ed8dce027c059b9a047fd6c2403a8e5a68d22fa0c5de9eaa356274"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.400+0/Singular.v404.101.400.x86_64-linux-musl-cxx03.tar.gz"
[[Singular]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5c7a48c649f121d65d8fdc16a3fee2ac25fb3eef"
libc = "musl"
os = "linux"

    [[Singular.download]]
    sha256 = "8ab5aff5db2eead2292abde3f87e5903a842eefbf5fb71b0a4aca115c2e4a8b1"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.400+0/Singular.v404.101.400.x86_64-linux-musl-cxx11.tar.gz"
[[Singular]]
arch = "x86_64"
git-tree-sha1 = "f1c288c20876a86ddb79ed9f421aa189f64c694f"
os = "freebsd"

    [[Singular.download]]
    sha256 = "2d3c16609268e710700904d26d6654cefc103d5f6ed0cd74fb4b9b9d5744e753"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.400+0/Singular.v404.101.400.x86_64-unknown-freebsd.tar.gz"
